---
http_interactions:
- request:
    method: get
    uri: http://fantasysports.yahooapis.com/fantasy/v2/league/346.l.115003/settings
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - OAuth gem v0.4.7
      Authorization:
      - OAuth oauth_consumer_key="dj0yJmk9TXl6TUNoUjF6WEVSJmQ9WVdrOU9UTnViMEZ5TjJjbWNHbzlNQS0tJnM9Y29uc3VtZXJzZWNyZXQmeD01Zg--",
        oauth_nonce="yMLJv86at6CQEc3AmpmQSR78kassWfx14HjdQvJL5s", oauth_signature="wVfiP41yyMm4RIQnuMwzK9729EM%3D",
        oauth_signature_method="HMAC-SHA1", oauth_timestamp="1441835888", oauth_token="A%3DHhMyRcff4yBPX5854TC63vReAG7fMMpB5SJjN6pZYmbE9Vc0GbGCZwsCMJwtKrkaa3lzK5qWNdhwqZMdHMUp1JRnk0gi80veQkGrS3ej622.XoW8VNKpkSdY56eIBtiVYtStfVEhbSRvBic3ak7_.go64H7ZdwzVcaTME3B_cfsjWSK0EUTXb3ivbZCTN1i.qrUV0aM4qFGpMEJEXkrKa7hAtyzJcnEtfvoFWRVlakY49i.D8BSpsEpr0xGvt44ZY2KEVu.mN1F3pwngHQFQfSAEyHlMzP1zgJcEQudHDnHOOvdGdoPsAh8h5mUXUNwyjeaicF7Fpd_WmldkOznjSH4EwF0iEdifHYcwZehEtTJAGsKhxUenIQjBTvUZUY6gbkOGqDxacIwKQJ0P3Ixljmcn7XGbkpPnc_SNtDeEZuX82NGpWmGwRPF6VovlykAgYofSwaIxKi3sCScsQQjlTRbZZQ.Jv.MXahriHdUqt4QN3.uYGk5C5AQ39x.xPS0H4o5VN4FvUC8bXfjUNVeOIv9x_ny02SX61_NzzZ80DqelSJYryur3CzF1kuqf2L1FzDBy8IeTv.P5KbOrTILgIwAal6YU8FJ.XCGPfUfYZh680DG_Q5fzw_WhjZ7gcL7PdGaduZ1GaI8OcHtdTUqJ.ml3xskmpnjeHuaQS9LmdnbTl2bY4Y10LCHt2N1k3qdFvFkdxvtGL3AVK.Tvf0zRkUVA7TmA0Steex77aoA2YNihCm0VxaYamKeif6twUIcsmS9blM8INn_Z3v2w0cTnTDE.0TQgeCmZis91E.BIihTOO.h_2VS6C1cKKEvbsg--",
        oauth_version="1.0"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Wed, 09 Sep 2015 21:58:08 GMT
      P3p:
      - policyref="http://info.yahoo.com/w3c/p3p.xml", CP="CAO DSP COR CUR ADM DEV
        TAI PSA PSD IVAi IVDi CONi TELo OTPi OUR DELi SAMi OTRi UNRi PUBi IND PHY
        ONL UNI PUR FIN COM NAV INT DEM CNT STA POL HEA PRE LOC GOV"
      X-Yahoo-Host:
      - fanos193.sports.bf1.yahoo.com
      Set-Cookie:
      - SPTB=d=ms0Yz5vVN3Ntw1rn_arofr0VfcWKarId.pHvzk7SzJDqjMc6Yd6jgMX3PHcCHOA2eERSCzNNW49eK0bsY8xHBAT5sLKlQqUajHzzFV05GhM-&v=1;
        expires=Fri, 09-Oct-2015 21:58:08 GMT; path=/; domain=fantasysports.yahooapis.com
      Cache-Control:
      - private,max-age=0,stale-while-revalidate=0
      Content-Type:
      - application/xml; charset=utf-8
      Vary:
      - Accept-Encoding
      X-Frame-Options:
      - SAMEORIGIN
      Content-Length:
      - '1761'
      Age:
      - '0'
      Via:
      - http/1.1 r46.ycpi.bf1.yahoo.net (ApacheTrafficServer [cMsSf ]), http/1.1 r13.ycpi.nyc.yahoo.net
        (ApacheTrafficServer [cMsSf ])
      Server:
      - ATS
      Connection:
      - keep-alive
    body:
      encoding: ASCII-8BIT
      string: |
        <?xml version="1.0" encoding="UTF-8"?>
        <fantasy_content xml:lang="en-US" yahoo:uri="http://fantasysports.yahooapis.com/fantasy/v2/league/346.l.115003/settings" time="54.08501625061ms" copyright="Data provided by Yahoo! and STATS, LLC" refresh_rate="31" xmlns:yahoo="http://www.yahooapis.com/v1/base.rng" xmlns="http://fantasysports.yahooapis.com/fantasy/v2/base.rng">
         <league>
          <league_key>346.l.115003</league_key>
          <league_id>115003</league_id>
          <name>Settlers of Baseball 4.0</name>
          <url>http://baseball.fantasysports.yahoo.com/b1/115003</url>
          <league_chat_id>c12nfxbpjxwwg8523ntywmu92hre8wa</league_chat_id>
          <draft_status>postdraft</draft_status>
          <num_teams>10</num_teams>
          <edit_key>2015-09-10</edit_key>
          <weekly_deadline/>
          <league_update_timestamp>1441783680</league_update_timestamp>
          <scoring_type>headpoint</scoring_type>
          <league_type>private</league_type>
          <renew>328_91021</renew>
          <renewed/>
          <short_invitation_url>https://yho.com/mlb?l=115003&amp;k=da09ab4cf9a49564</short_invitation_url>
          <is_pro_league>0</is_pro_league>
          <current_week>22</current_week>
          <start_week>1</start_week>
          <start_date>2015-04-05</start_date>
          <end_week>24</end_week>
          <end_date>2015-09-27</end_date>
          <game_code>mlb</game_code>
          <season>2015</season>
          <settings>
           <draft_type>live</draft_type>
           <is_auction_draft>0</is_auction_draft>
           <scoring_type>headpoint</scoring_type>
           <persistent_url>http://baseball.fantasysports.yahoo.com/league/settlers_of_baseball4</persistent_url>
           <uses_playoff>1</uses_playoff>
           <has_playoff_consolation_games>1</has_playoff_consolation_games>
           <playoff_start_week>23</playoff_start_week>
           <uses_playoff_reseeding>0</uses_playoff_reseeding>
           <uses_lock_eliminated_teams>0</uses_lock_eliminated_teams>
           <num_playoff_teams>4</num_playoff_teams>
           <num_playoff_consolation_teams>4</num_playoff_consolation_teams>
           <waiver_type>R</waiver_type>
           <waiver_rule>all</waiver_rule>
           <uses_faab>0</uses_faab>
           <draft_time>1427936400</draft_time>
           <draft_pick_time>75</draft_pick_time>
           <post_draft_players>W</post_draft_players>
           <max_teams>12</max_teams>
           <waiver_time>2</waiver_time>
           <trade_end_date>2015-08-23</trade_end_date>
           <trade_ratify_type>vote</trade_ratify_type>
           <trade_reject_time>1</trade_reject_time>
           <player_pool>ALL</player_pool>
           <cant_cut_list>none</cant_cut_list>
           <can_trade_draft_picks>1</can_trade_draft_picks>
           <roster_positions>
            <roster_position>
             <position>C</position>
             <position_type>B</position_type>
             <count>1</count>
            </roster_position>
            <roster_position>
             <position>1B</position>
             <position_type>B</position_type>
             <count>1</count>
            </roster_position>
            <roster_position>
             <position>2B</position>
             <position_type>B</position_type>
             <count>1</count>
            </roster_position>
            <roster_position>
             <position>3B</position>
             <position_type>B</position_type>
             <count>1</count>
            </roster_position>
            <roster_position>
             <position>SS</position>
             <position_type>B</position_type>
             <count>1</count>
            </roster_position>
            <roster_position>
             <position>OF</position>
             <position_type>B</position_type>
             <count>3</count>
            </roster_position>
            <roster_position>
             <position>Util</position>
             <position_type>B</position_type>
             <count>2</count>
            </roster_position>
            <roster_position>
             <position>SP</position>
             <position_type>P</position_type>
             <count>4</count>
            </roster_position>
            <roster_position>
             <position>RP</position>
             <position_type>P</position_type>
             <count>2</count>
            </roster_position>
            <roster_position>
             <position>P</position>
             <position_type>P</position_type>
             <count>2</count>
            </roster_position>
            <roster_position>
             <position>BN</position>
             <count>4</count>
            </roster_position>
            <roster_position>
             <position>DL</position>
             <count>2</count>
            </roster_position>
           </roster_positions>
           <stat_categories>
            <stats>
             <stat>
              <stat_id>60</stat_id>
              <enabled>1</enabled>
              <name>H/AB</name>
              <display_name>H/AB</display_name>
              <sort_order>1</sort_order>
              <position_type>B</position_type>
              <stat_position_types>
               <stat_position_type>
                <position_type>B</position_type>
                <is_only_display_stat>1</is_only_display_stat>
               </stat_position_type>
              </stat_position_types>
              <is_only_display_stat>1</is_only_display_stat>
             </stat>
             <stat>
              <stat_id>7</stat_id>
              <enabled>1</enabled>
              <name>Runs</name>
              <display_name>R</display_name>
              <sort_order>1</sort_order>
              <position_type>B</position_type>
              <stat_position_types>
               <stat_position_type>
                <position_type>B</position_type>
               </stat_position_type>
              </stat_position_types>
             </stat>
             <stat>
              <stat_id>9</stat_id>
              <enabled>1</enabled>
              <name>Singles</name>
              <display_name>1B</display_name>
              <sort_order>1</sort_order>
              <position_type>B</position_type>
              <stat_position_types>
               <stat_position_type>
                <position_type>B</position_type>
               </stat_position_type>
              </stat_position_types>
             </stat>
             <stat>
              <stat_id>10</stat_id>
              <enabled>1</enabled>
              <name>Doubles</name>
              <display_name>2B</display_name>
              <sort_order>1</sort_order>
              <position_type>B</position_type>
              <stat_position_types>
               <stat_position_type>
                <position_type>B</position_type>
               </stat_position_type>
              </stat_position_types>
             </stat>
             <stat>
              <stat_id>11</stat_id>
              <enabled>1</enabled>
              <name>Triples</name>
              <display_name>3B</display_name>
              <sort_order>1</sort_order>
              <position_type>B</position_type>
              <stat_position_types>
               <stat_position_type>
                <position_type>B</position_type>
               </stat_position_type>
              </stat_position_types>
             </stat>
             <stat>
              <stat_id>12</stat_id>
              <enabled>1</enabled>
              <name>Home Runs</name>
              <display_name>HR</display_name>
              <sort_order>1</sort_order>
              <position_type>B</position_type>
              <stat_position_types>
               <stat_position_type>
                <position_type>B</position_type>
               </stat_position_type>
              </stat_position_types>
             </stat>
             <stat>
              <stat_id>13</stat_id>
              <enabled>1</enabled>
              <name>Runs Batted In</name>
              <display_name>RBI</display_name>
              <sort_order>1</sort_order>
              <position_type>B</position_type>
              <stat_position_types>
               <stat_position_type>
                <position_type>B</position_type>
               </stat_position_type>
              </stat_position_types>
             </stat>
             <stat>
              <stat_id>16</stat_id>
              <enabled>1</enabled>
              <name>Stolen Bases</name>
              <display_name>SB</display_name>
              <sort_order>1</sort_order>
              <position_type>B</position_type>
              <stat_position_types>
               <stat_position_type>
                <position_type>B</position_type>
               </stat_position_type>
              </stat_position_types>
             </stat>
             <stat>
              <stat_id>18</stat_id>
              <enabled>1</enabled>
              <name>Walks</name>
              <display_name>BB</display_name>
              <sort_order>1</sort_order>
              <position_type>B</position_type>
              <stat_position_types>
               <stat_position_type>
                <position_type>B</position_type>
               </stat_position_type>
              </stat_position_types>
             </stat>
             <stat>
              <stat_id>21</stat_id>
              <enabled>1</enabled>
              <name>Strikeouts</name>
              <display_name>K</display_name>
              <sort_order>0</sort_order>
              <position_type>B</position_type>
              <stat_position_types>
               <stat_position_type>
                <position_type>B</position_type>
               </stat_position_type>
              </stat_position_types>
             </stat>
             <stat>
              <stat_id>50</stat_id>
              <enabled>1</enabled>
              <name>Innings Pitched</name>
              <display_name>IP</display_name>
              <sort_order>1</sort_order>
              <position_type>P</position_type>
              <stat_position_types>
               <stat_position_type>
                <position_type>P</position_type>
               </stat_position_type>
              </stat_position_types>
             </stat>
             <stat>
              <stat_id>28</stat_id>
              <enabled>1</enabled>
              <name>Wins</name>
              <display_name>W</display_name>
              <sort_order>1</sort_order>
              <position_type>P</position_type>
              <stat_position_types>
               <stat_position_type>
                <position_type>P</position_type>
               </stat_position_type>
              </stat_position_types>
             </stat>
             <stat>
              <stat_id>29</stat_id>
              <enabled>1</enabled>
              <name>Losses</name>
              <display_name>L</display_name>
              <sort_order>0</sort_order>
              <position_type>P</position_type>
              <stat_position_types>
               <stat_position_type>
                <position_type>P</position_type>
               </stat_position_type>
              </stat_position_types>
             </stat>
             <stat>
              <stat_id>32</stat_id>
              <enabled>1</enabled>
              <name>Saves</name>
              <display_name>SV</display_name>
              <sort_order>1</sort_order>
              <position_type>P</position_type>
              <stat_position_types>
               <stat_position_type>
                <position_type>P</position_type>
               </stat_position_type>
              </stat_position_types>
             </stat>
             <stat>
              <stat_id>37</stat_id>
              <enabled>1</enabled>
              <name>Earned Runs</name>
              <display_name>ER</display_name>
              <sort_order>0</sort_order>
              <position_type>P</position_type>
              <stat_position_types>
               <stat_position_type>
                <position_type>P</position_type>
               </stat_position_type>
              </stat_position_types>
             </stat>
             <stat>
              <stat_id>39</stat_id>
              <enabled>1</enabled>
              <name>Walks</name>
              <display_name>BB</display_name>
              <sort_order>0</sort_order>
              <position_type>P</position_type>
              <stat_position_types>
               <stat_position_type>
                <position_type>P</position_type>
               </stat_position_type>
              </stat_position_types>
             </stat>
             <stat>
              <stat_id>42</stat_id>
              <enabled>1</enabled>
              <name>Strikeouts</name>
              <display_name>K</display_name>
              <sort_order>1</sort_order>
              <position_type>P</position_type>
              <stat_position_types>
               <stat_position_type>
                <position_type>P</position_type>
               </stat_position_type>
              </stat_position_types>
             </stat>
             <stat>
              <stat_id>83</stat_id>
              <enabled>1</enabled>
              <name>Quality Starts</name>
              <display_name>QS</display_name>
              <sort_order>1</sort_order>
              <position_type>P</position_type>
              <stat_position_types>
               <stat_position_type>
                <position_type>P</position_type>
               </stat_position_type>
              </stat_position_types>
             </stat>
             <stat>
              <stat_id>84</stat_id>
              <enabled>1</enabled>
              <name>Blown Saves</name>
              <display_name>BSV</display_name>
              <sort_order>0</sort_order>
              <position_type>P</position_type>
              <stat_position_types>
               <stat_position_type>
                <position_type>P</position_type>
               </stat_position_type>
              </stat_position_types>
             </stat>
            </stats>
           </stat_categories>
           <stat_modifiers>
            <stats>
             <stat>
              <stat_id>7</stat_id>
              <value>1</value>
             </stat>
             <stat>
              <stat_id>9</stat_id>
              <value>1</value>
             </stat>
             <stat>
              <stat_id>10</stat_id>
              <value>2</value>
             </stat>
             <stat>
              <stat_id>11</stat_id>
              <value>3</value>
             </stat>
             <stat>
              <stat_id>12</stat_id>
              <value>4</value>
             </stat>
             <stat>
              <stat_id>13</stat_id>
              <value>1</value>
             </stat>
             <stat>
              <stat_id>16</stat_id>
              <value>2</value>
             </stat>
             <stat>
              <stat_id>18</stat_id>
              <value>1</value>
             </stat>
             <stat>
              <stat_id>21</stat_id>
              <value>-1</value>
             </stat>
             <stat>
              <stat_id>50</stat_id>
              <value>0.5</value>
             </stat>
             <stat>
              <stat_id>28</stat_id>
              <value>5</value>
             </stat>
             <stat>
              <stat_id>29</stat_id>
              <value>-3</value>
             </stat>
             <stat>
              <stat_id>32</stat_id>
              <value>4</value>
             </stat>
             <stat>
              <stat_id>37</stat_id>
              <value>-1</value>
             </stat>
             <stat>
              <stat_id>39</stat_id>
              <value>-.25</value>
             </stat>
             <stat>
              <stat_id>42</stat_id>
              <value>1</value>
             </stat>
             <stat>
              <stat_id>83</stat_id>
              <value>4</value>
             </stat>
             <stat>
              <stat_id>84</stat_id>
              <value>-2</value>
             </stat>
            </stats>
           </stat_modifiers>
           <max_weekly_adds>2</max_weekly_adds>
           <season_type>full</season_type>
           <min_innings_pitched>10</min_innings_pitched>
          </settings>
         </league>
        </fantasy_content>
    http_version: 
  recorded_at: Wed, 09 Sep 2015 21:58:08 GMT
recorded_with: VCR 2.9.3
